import React, { ReactNode } from "react";
import Head from "next/head";
import Header from "./header/Header";
import Footer from "./footer/Footer";
import { GridContainer } from "@/styles/layout";
import styled from "styled-components";

type Props = {
  children?: ReactNode;
};

const Main = styled(GridContainer)`
  padding: 50px 0 100px 0;
  margin-top: 114px;

  @media (max-width: ${({ theme }) => theme.media.medium_width}) {
    padding: 0 0 50px 0;
  }
`;

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Dananz Interior</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>{children}</Main>
      <Footer />
    </>
  );
}
